In [1]:
import pandas as pd
df = pd.read_csv('C:/Users/dlwnr/graduation_thesis/data/use_data/2021년-서울서베이-시민_데이터.csv')
df

C:\Users\dlwnr\AppData\Local\Temp\ipykernel_23400\1248089506.py:2: DtypeWarning: Columns (114) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('C:/Users/dlwnr/graduation_thesis/data/use_data/2021년-서울서베이-시민_데이터.csv')

,ID,ARA1,FAM1,FAM2,SEX,YEAR,MAR,HOU1,HOU2,Q1_1,...,wtb1,wtb2,DE1,DE2,DE3,DE4,DE5,DE6,DE7,DE8
0,1,110,3.0,3.0,1,1975,1,1,1,3,...,1040.033,0.629,1.0,3.0,3.0,1.0,3.0,1.0,1.0,2.0
1,2,110,3.0,3.0,2,1962,1,1,1,1,...,839.893,0.508,2.0,4.0,3.0,1.0,3.0,1.0,1.0,2.0
2,3,110,2.0,2.0,2,1954,1,1,1,3,...,1093.463,0.662,2.0,5.0,3.0,1.0,2.0,1.0,1.0,4.0
3,4,110,3.0,3.0,1,1958,1,1,1,2,...,735.317,0.445,1.0,5.0,3.0,1.0,3.0,1.0,1.0,1.0
4,5,110,3.0,2.0,2,1984,1,1,2,1,...,950.213,0.575,2.0,2.0,3.0,1.0,3.0,1.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4916,740,3.0,3.0,1,1997,2,2,1,1,...,336.934,0.204,1.0,1.0,3.0,2.0,3.0,2.0,5.0,2.0
4996,3795,590,3.0,3.0,1,2001,2,2,2,3,...,1009.090,0.611,1.0,1.0,3.0,2.0,3.0,2.0,4.0,4.0
4997,4743,710,3.0,3.0,2,1993,2,4,3,1,...,6159.345,3.727,2.0,1.0,3.0,4.0,3.0,2.0,5.0,2.0
4998,4810,740,1.0,1.0,2,1970,3,2,1,1,...,1756.586,1.063,2.0,4.0,3.0,2.0,1.0,3.0,5.0,2.0
4999,93,110,3.0,3.0,2,1993,2,5,2,1,...,242.303,0.147,2.0,1.0,3.0,4.0,3.0,2.0,1.0,2.0

In [2]:
#sns

# 열을 추가하자(특졍열에 맞춰서)
# 아래는 df['Q11]이 어떤 값 일때 df['Q15']를 원하는 값으로 변경해주었다.

df.loc[df['Q11'] == 8,'Q15'] = 0
df.loc[df['Q11'] == 1,'Q15']= 1.000000
df.loc[df['Q11'] == 2,'Q15'] = 0.142857
df.loc[df['Q11'] == 3,'Q15'] = 0.033333
df.loc[df['Q11'] == 4,'Q15'] = 0.005555
df.loc[df['Q11'] == 5,'Q15'] = 0.002740

# #NULL!값을 0으로 바꿔주자
my_list=df['Q11_1']

for index, value in enumerate(my_list):
    if value == '#NULL!' :
      my_list[index] = 0


# #NULL!바꾸고 int형으로 변환
df['Q11_1'] = list(map(int, my_list))

df['raw_count']=df['Q11_1']*df['Q15']

C:\Users\dlwnr\AppData\Local\Temp\ipykernel_23400\1515021110.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  my_list[index] = 0

In [3]:
#연령
df['new_age'] = 2021
df['new_age'] = df['new_age'] - df['YEAR']

In [6]:
#돈


#상승
df.loc[((df['Q24_1']==1) & (df['Q24_2A'] == '1.00'))|((df['Q24_1']==2) & (df['Q24_2B'] == '1.00')), 'Q15'] = '상승'
#하강
df.loc[(df['Q24_1']==1) & (df['Q24_2A'] == '2.00')|((df['Q24_1']==2) & (df['Q24_2B'] == '2.00')),'Q15']= '하강'
#아웃
df.loc[(df['Q24_1']==1) & (df['Q24_2A'] == '3.00')|((df['Q24_1']==2) & (df['Q24_2B'] == '3.00')),'Q15'] = '해고 및 폐업'
#변화없음
df.loc[(df['Q24_1']==1) & (df['Q24_2A'] == '4.00')|((df['Q24_1']==2) & (df['Q24_2B'] == '4.00'))|(df['Q24_1']==3),'Q15'] = '변호없음'

In [7]:
#학력

#고등학교
df.loc[(df['DQ1_1']==1) | (df['DQ1_1']==2) |(df['DQ1_1']==3) | (df['DQ1_1']==4), 'DQ1_2'] = '고등학교'
#대학교
df.loc[(df['DQ1_1']==5)|(df['DQ1_1']==6),'DQ1_2']= '대학교'
#대학원
df.loc[(df['DQ1_1']==7),'DQ1_2'] = '대학원'

In [8]:
# 성별

#남
df.loc[(df['SEX']==1) , 'Q3_1_1'] = '남'
#여
df.loc[(df['SEX']==2) , 'Q3_1_1'] = '여'

In [9]:
# 재택근무


df['Q20'].value_counts()

# #NULL!값을 0으로 바꿔주자
jh_list=df['Q20']

for index, value in enumerate(jh_list):
    if value == '#NULL!' :
      jh_list[index] = 0


# #NULL!바꾸고 int형으로 변환
df['Q20'] = list(map(int, jh_list))
df['Q20'].value_counts()

#재택근무 경험 있다.
df.loc[(df['Q20']==1) , 'Q3_1_2'] = '경험 있음'
#재택근무 경험 없다.
df.loc[(df['Q20']==2) , 'Q3_1_2'] = '경험 없음'
#일을 하지 않는다.
df.loc[(df['Q20']==0) , 'Q3_1_2'] = '일을 안함'

C:\Users\dlwnr\AppData\Local\Temp\ipykernel_23400\2944805105.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jh_list[index] = 0

In [10]:
use_df=df[['Q22','Q3_1_1','Q15','new_age','DQ1_2','Q3_1_2','raw_count']]
use_df.columns=['sad','sex','money','age','school','jobhome','sns']
use_df.to_csv('C:/Users/dlwnr/a/thesis_code/use.csv')

In [11]:
use_df

      sad sex    money  age school jobhome        sns
0       5   남       하강   46    대학교   경험 있음   0.428571
1       6   여     변호없음   59    대학교   경험 있음  10.000000
2       6   여     변호없음   67    대학교   일을 안함   5.000000
3       8   남       하강   63    대학교   경험 없음   5.000000
4       6   여       하강   37    대학교   경험 없음   7.000000
...   ...  ..      ...  ...    ...     ...        ...
4995   10   남  해고 및 폐업   24    대학교   경험 있음  10.000000
4996   10   남       하강   20    대학교   일을 안함   5.000000
4997    6   여     변호없음   28    대학교   경험 있음   0.142857
4998    1   여     변호없음   51    대학교   경험 있음   3.000000
4999    8   여     변호없음   28    대학교   경험 없음  10.000000

[5000 rows x 7 columns]

In [ ]:
import statsmodels.formula.api as sm 


model = sm.ols(formula = 'Q22 ~ C(group) + 0',data=all).fit() 
model.summary()

In [14]:
import statsmodels.formula.api as sm 


model = sm.ols(formula = 'sad ~ age+sns+school+money+sex+jobhome',data=use_df).fit() 
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    sad   R-squared:                       0.024
Model:                            OLS   Adj. R-squared:                  0.022
Method:                 Least Squares   F-statistic:                     12.38
Date:                Tue, 27 Sep 2022   Prob (F-statistic):           1.68e-21
Time:                        13:33:38   Log-Likelihood:                -11105.
No. Observations:                5000   AIC:                         2.223e+04
Df Residuals:                    4989   BIC:                         2.230e+04
Df Model:                          10
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            4.6620      0.147     31.621      0.000       4.373       4.951
school[T.대학교]        0.1071      0.079      1.353      0.176      -0.048       0.262
school[T.대학원]       -0.1732      0.178     -0.974      0.330      -0.522       0.175
money[T.상승]          0.1089      0.210      0.518      0.605      -0.303       0.521
money[T.하강]          0.7789      0.082      9.448      0.000       0.617       0.941
money[T.해고 및 폐업]     0.5691      0.191      2.984      0.003       0.195       0.943
sex[T.여]             0.2738      0.066      4.179      0.000       0.145       0.402
jobhome[T.경험 있음]    -0.0721      0.084     -0.854      0.393      -0.238       0.093
jobhome[T.일을 안함]     0.1030      0.081      1.269      0.204      -0.056       0.262
age                  0.0054      0.002      2.410      0.016       0.001       0.010
sns                  0.0009      0.003      0.336      0.737      -0.005       0.006
==============================================================================
Omnibus:                      208.358   Durbin-Watson:                   1.455
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              226.208
Skew:                          -0.505   Prob(JB):                     7.58e-50
Kurtosis:                       2.743   Cond. No.                         327.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Durbin-Watson(더 빈 왓슨, DW검정)

위의 예시에서는 0.714로 나타나 있다. 잔차의 독립성을 확인할 수 있는 수치다.

0이면 잔차들이 양의 자기 상관을 가진다.
2이면 자기 상관이 없는 독립성을 가진다.
4이면 잔차들이 음의 자기 상관을 가진다.
보통 1.5에서 2.5 사이이면 독립으로 판단하고 회귀 모형이 적합하다는 것을 의미한다. 만약 0이나 4에 가깝다면 잔차들이 자기상관을 가지고 있다는 의미이므로 t, F, R제곱을 실제보다 증가시켜 유의미하지 않은 결과를 유의미한 결과로 왜곡하게 한다.

In [15]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
 

 
X_train = use_df[['age']]
 
def feature_engineering_XbyVIF(X_train):
    vif = pd.DataFrame()
    
    vif['VIF_Factor'] = [variance_inflation_factor(X_train.values, i) for i in range(X_train.shape[1])]
    vif['Feature'] = X_train.columns
    return vif
vif = feature_engineering_XbyVIF(X_train)
print(vif)

ValueError: zero-size array to reduction operation maximum which has no identity